package io.github.lionheartlattice.entity.user_center.dept;

import com.easy.query.core.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.math.BigDecimal;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link Dept }
 *
 * @author
 * @easy-query-dto schema: normal
 */
@Data
public class DeptUpdateDTO {
    /**
     * 用户ID
     */
    @Schema(description = "唯一标识")
    @Column(value = "id")
    private BigDecimal id;

    @NotNull
    @Schema(description = "部门名称", requiredMode = Schema.RequiredMode.REQUIRED)
    private String name;
    /**
     * 父级ID
     */
    @NotNull
    @Schema(description = "父级ID", requiredMode = Schema.RequiredMode.REQUIRED)
    private BigDecimal pid;
    /**
     * 默认分配角色ID
     */
    @Schema(description = "默认分配角色ID")
    private BigDecimal defaultRoleId;
    /**
     * 排序
     */
    @Schema(description = "排序")
    private Integer sort;
    /**
     * 备注
     */
    @Schema(description = "备注")
    private String remark;

}
