package io.github.lionheartlattice.entity.user_center.dto;

import com.easy.query.core.annotation.Column;
import io.github.lionheartlattice.entity.user_center.po.Tenant;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link Tenant }
 *
 * @author lionheart
 * @easy-query-dto schema: normal
 */
@Data
public class TenantUpdateDTO {

    /**
     * 租户ID
     */
    @Schema(description = "租户ID", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(value = "id")
    @NotNull
    private BigDecimal id;

    /**
     * 租户名称
     */
    @Schema(description = "租户名称", requiredMode = Schema.RequiredMode.REQUIRED)
    private String name;

    /**
     * 联系人ID (管理员)
     */
    @Schema(description = "联系人ID", requiredMode = Schema.RequiredMode.REQUIRED)
    private String managerUserId;

    /**
     * ��系电话
     */
    @Schema(description = "联系电话", requiredMode = Schema.RequiredMode.REQUIRED)
    private String managerUserPhone;

    /**
     * 是否锁定
     */
    @Schema(description = "是否锁定", requiredMode = Schema.RequiredMode.REQUIRED)
    private Boolean isLock;

    /**
     * 过期时间
     */
    @Schema(description = "过期时间")
    private LocalDateTime expireTime;

    /**
     * 备注
     */
    @Schema(description = "备注")
    private String remark;

}

