package io.github.lionheartlattice.entity.user_center.dto;


import com.easy.query.core.annotation.Column;
import io.github.lionheartlattice.entity.base.PageRequest;
import io.github.lionheartlattice.entity.user_center.po.User;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link User }
 *
 * @author
 * @easy-query-dto schema: response
 */
@Data
public class UserPageDTO extends PageRequest<UserPageDTO> {
    /**
     * 用户ID
     */
    @Column(value = "id")
    private Long id;
    /**
     * 用户名
     */
    @Schema(description = "用户名")
    private String username;
    /**
     * 手机号
     */
    @Schema(description = "手机号")
    private String phone;
    /**
     * 昵称
     */
    @Schema(description = "昵称")
    private String nickname;
    /**
     * 性别 未知-男-女
     */
    @Schema(description = "性别 未知-男-女")
    private String sex;

    /**
     * 身份证
     */
    @Schema(description = "身份证")
    private String idCard;
    /**
     * 邮箱地址
     */
    @Schema(description = "邮箱地址")
    private String email;

    /**
     * 创建人ID
     */
    @Schema(description = "创建人ID")
    private Long createId;
    /**
     * 更新人ID
     */
    @Schema(description = "更新人ID")
    private Long updateId;


}
