package io.github.lionheartlattice.entity.user_center.dto;


import io.github.lionheartlattice.entity.user_center.po.User;
import lombok.Data;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDate;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link User }
 *
 * @author
 * @easy-query-dto schema: request
 */
@Data
public class UserDTO {


    /**
     * 用户名
     */
    @Schema(description = "用户名", requiredMode = Schema.RequiredMode.REQUIRED)
    private String username;
    /**
     * 密码
     */
    @Schema(description = "密码", requiredMode = Schema.RequiredMode.REQUIRED)
    private String pwd;
    /**
     * 手机号
     */
    @Schema(description = "手机号")
    private String phone;
    /**
     * 昵称
     */
    @Schema(description = "昵称")
    private String nickname;
    /**
     * 性别 未知-男-女
     */
    @Schema(description = "性别 未知-男-女")
    private String sex;
    /**
     * 生日
     */
    @Schema(description = "生日")
    private LocalDate birthday = LocalDate.now();

    /**
     * 身份证
     */
    @Schema(description = "身份证")
    private String idCard;
    /**
     * 邮箱地址
     */
    @Schema(description = "邮箱地址")
    private String email;


}
