package io.github.lionheartlattice.entity.user_center.dto;


import com.easy.query.core.annotation.Column;
import io.github.lionheartlattice.entity.user_center.po.User;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.time.LocalDate;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link User }
 *
 * @author
 * @easy-query-dto schema: normal
 */
@Data
public class UserUpdateDTO {


    /**
     * 用户ID
     */
    @Schema(description = "用户ID")
    @Column(value = "id")
    @NotNull
    private Long id;
    /**
     * 用户名
     */
    @Schema(description = "用户名")
    private String username;
    /**
     * 密码
     */
    @Schema(description = "密码")
    private String pwd;
    /**
     * 手机号
     */
    @Schema(description = "手机号")
    private String phone;
    /**
     * 昵称
     */
    @Schema(description = "昵称")
    private String nickname;
    /**
     * 性别 未知-男-女
     */
    @Schema(description = "性别 未知-男-女")
    private String sex;
    /**
     * 生日
     */
    @Schema(description = "生日")
    private LocalDate birthday;
    /**
     * 头像base64
     */
    @Schema(description = "头像base64")
    private String logo;
    /**
     * 身份证
     */
    @Schema(description = "身份证")
    private String idCard;
    /**
     * 邮箱地址
     */
    @Schema(description = "邮箱地址")
    private String email;


}
